# Generated by Django 3.0 on 2020-09-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_applications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={},
        ),
    ]
