# Generated by Django 3.0 on 2020-09-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200929_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Заявка cо страницы контактов', 'verbose_name_plural': 'Заявка со страницы контактов'},
        ),
    ]
